name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install -g web-ext

      - name: Build extension
        run: ./build.sh
      - name: Publish to Mozilla
        run: |
          cd build/firefox/bin
          "$(npm config get prefix)"/bin/web-ext sign -a . -s ../src || true
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}

      - name: Publish to Chrome
        run: |
          PACKAGE=$(find build/chromium/bin -type f -name "*.zip")
          CWS_ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CWS_CLIENT_ID}&client_secret=${CWS_CLIENT_SECRET}&refresh_token=${CWS_REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
          curl -H "Authorization: Bearer ${CWS_ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T $PACKAGE "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${CWS_EXTENSION_ID}"
          curl -H "Authorization: Bearer ${CWS_ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST "https://www.googleapis.com/chromewebstore/v1.1/items/${CWS_EXTENSION_ID}/publish" || true
        env:
          CWS_CLIENT_ID: ${{ secrets.CWS_CLIENT_ID }}
          CWS_CLIENT_SECRET: ${{ secrets.CWS_CLIENT_SECRET }}
          CWS_REFRESH_TOKEN: ${{ secrets.CWS_REFRESH_TOKEN }}
          CWS_EXTENSION_ID: ${{ secrets.CWS_EXTENSION_ID }}

      - name: Publish to Edge
        run: |
          PACKAGE=$(find build/chromium/bin -type f -name "*.zip")
          MSE_ACCESS_TOKEN=$(curl "$MSE_ACCESS_TOKEN_URL" -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "client_id=${MSE_CLIENT_ID}&client_secret=${MSE_CLIENT_SECRET}&scope=https://api.addons.microsoftedge.microsoft.com/.default&grant_type=client_credentials&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
          curl -H "Authorization: Bearer ${MSE_ACCESS_TOKEN}" -H "Content-Type: application/zip" -X POST -T $PACKAGE "https://api.addons.microsoftedge.microsoft.com/v1/products/$MSE_EXTENSION_ID/submissions/draft/package"
          curl -H "Authorization: Bearer ${MSE_ACCESS_TOKEN}" -H "Content-Length: 0" -X POST "https://api.addons.microsoftedge.microsoft.com/v1/products/$MSE_EXTENSION_ID/submissions"
        env:
          MSE_CLIENT_ID: ${{ secrets.MSE_CLIENT_ID }}
          MSE_CLIENT_SECRET: ${{ secrets.MSE_CLIENT_SECRET }}
          MSE_ACCESS_TOKEN_URL: ${{ secrets.MSE_ACCESS_TOKEN_URL }}
          MSE_EXTENSION_ID: ${{ secrets.MSE_EXTENSION_ID }}
