name: Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install -g web-ext
      - name: Lint extension
        run: |
          "$(npm config get prefix)/bin/web-ext" lint
      - name: Build extension
        run: |
          "$(npm config get prefix)/bin/web-ext" build
      - name: Publish extension
        run: |
          "$(npm config get prefix)/bin/web-ext" sign || true
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: web-ext-artifacts/*
